[project]
name = 'amm'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.mock-token]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-token-2]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-token-3]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-token-4]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.amm]
path = 'contracts/amm.clar'
clarity_version = 3
epoch = 'latest'

[contracts.amm-v2]
path = 'contracts/amm.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-token-v2]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-token-5]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-token-6]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
